language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
before_script:
  - "npm install -g nsp"
script:
  - "npm run test"
  - "nsp check"
  - "npm run build"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $githubToken
  local_dir: build
  on:
    branch: master